version: "3.9"
services:
  runtime-database:
    image: postgres:12.6
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=demo
    ports:
      - 5433:5432

  compile-database:
    image: postgres:12.6
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  database-admin:
    image: adminer
    restart: always
    ports:
      - 8081:8080
