name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.400
    - name: Restore dependencies
      run: dotnet tool restore && dotnet paket restore && dotnet restore
    - name: Build
      run: dotnet build --no-restore
